from PyQt5 import QtCore, QtGui, QtWidgets
import support


class Ui_Dialog(object):
    def change_ui(self):
        ICAO = self.ICAOINPUT.text()
        metar_final = support.metar_get(ICAO)
        if ICAO != '':
            self.label_11.setHidden(True)
            self.label_17.setHidden(True)
            self.label_13.setHidden(True)
            self.label_14.setHidden(True)
            self.label_12.setHidden(True)
            self.label_16.setHidden(True)

            #initialize the dictionary & variables
            dict = support.metar_dict(metar_final)
            cloud = ''

            if dict['clouds'][0] == 'CLR':
                cloud = 120
            else:
                cloud = dict['clouds'][0][3:]

            cloud = str(cloud).lstrip('0')

            cloudstring = 'Level(s) at: '
            for i in dict['clouds']:
                cloudstring += f'{i},'
            condition = support.Condition(dict['clouds'], dict['vis'], 110)

            #Primative exception handling
            if metar_final == 'nullbyte1':
                self.METARRAWOUTPUT.setText(f'Airport {ICAO.upper()} Is not an airport./does not report METAR.')
            else:
                self.METARRAWOUTPUT.setText(metar_final[:55])

            #Set user seen values to dictionary keys
                self.TIMEOUTPUT.setText(dict['time'])
                self.WINDOUTPUT.setText(dict['wind'])
                self.VISOUTPUT.setText(dict['vis'])
                self.CLOUDOUTPUT.setText((cloudstring))
                self.BAROOUTPUT.setText(dict['baro'])
                self.TEMPOUTPUT.setText(dict['temp'] + 'C*')
                self.DEWPOINT.setText(dict['dew'] + 'C*')
                self.CONDITIONOUTPUT.setText(str(condition))
                self.DENSITYOUTPUT.setText(str(support.densityalt(dict['baro'], dict['temp'])) + 'ft')

                #Setting Images to Correct situation for enviroment
                if condition == 'IFR': self.label_16.setHidden(False)
                if dict['vis'][1] == 'S':
                    if int(dict['vis'][0]) <= 3:
                        self.label_14.setHidden(False)
                if dict['vis'] == '1.25SM' or dict['vis'] == '1.5SM' or dict['vis'] == '1.75SM':
                    self.label_14.setHidden(False)

                if int(cloud) - 11 < 22: self.label_13.setHidden(False)
                if str(dict['temp'][0]) == 'M':
                    self.label_17.setHidden(False)
                else:
                    if int(dict['temp']) >= 20:
                        self.label_12.setHidden(False)
                for i in dict['wind']:
                    if i == 'G':
                        self.label_11.setHidden(False)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(466, 743)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 210, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 300, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 330, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 360, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 390, 131, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 420, 191, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 450, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 480, 121, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 510, 191, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 540, 161, 16))
        self.label_10.setObjectName("label_10")
        self.FAAWARNINGLABEL = QtWidgets.QLabel(Dialog)
        self.FAAWARNINGLABEL.setGeometry(QtCore.QRect(10, 700, 481, 51))
        self.FAAWARNINGLABEL.setObjectName("FAAWARNINGLABEL")
        self.INSTRUCTIONS = QtWidgets.QLabel(Dialog)
        self.INSTRUCTIONS.setGeometry(QtCore.QRect(20, 15, 441, 41))
        self.INSTRUCTIONS.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.INSTRUCTIONS.setObjectName("INSTRUCTIONS")
        self.GITHUBLINK = QtWidgets.QLabel(Dialog)
        self.GITHUBLINK.setGeometry(QtCore.QRect(10, 120, 441, 41))
        self.GITHUBLINK.setStyleSheet("font: 75 9pt \"Times New Roman\";")
        self.GITHUBLINK.setObjectName("INSTRUCTIONS")
        self.Extraspace = QtWidgets.QLabel(Dialog)
        self.Extraspace.setGeometry(QtCore.QRect(10, 140, 441, 41))
        self.Extraspace.setStyleSheet("font: 75 9pt \"Times New Roman\";")
        self.Extraspace.setObjectName("INSTRUCTIONS")
        self.ICAO = QtWidgets.QLabel(Dialog)
        self.ICAO.setGeometry(QtCore.QRect(20, 70, 61, 31))
        self.ICAO.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.ICAO.setObjectName("ICAO")
        self.ICAOINPUT = QtWidgets.QLineEdit(Dialog)
        self.ICAOINPUT.setGeometry(QtCore.QRect(70, 70, 221, 31))
        self.ICAOINPUT.setObjectName("ICAOINPUT")
        self.METARRAWOUTPUT = QtWidgets.QLabel(Dialog)
        self.METARRAWOUTPUT.setGeometry(QtCore.QRect(130, 200, 341, 41))
        self.METARRAWOUTPUT.setObjectName("METARRAWOUTPUT")
        self.TIMEOUTPUT = QtWidgets.QLabel(Dialog)
        self.TIMEOUTPUT.setGeometry(QtCore.QRect(110, 300, 321, 16))
        self.TIMEOUTPUT.setObjectName("TIMEOUTPUT")
        self.WINDOUTPUT = QtWidgets.QLabel(Dialog)
        self.WINDOUTPUT.setGeometry(QtCore.QRect(110, 330, 351, 16))
        self.WINDOUTPUT.setObjectName("WINDOUTPUT")
        self.VISOUTPUT = QtWidgets.QLabel(Dialog)
        self.VISOUTPUT.setGeometry(QtCore.QRect(130, 360, 341, 16))
        self.VISOUTPUT.setObjectName("VISOUTPUT")
        self.CLOUDOUTPUT = QtWidgets.QLabel(Dialog)
        self.CLOUDOUTPUT.setGeometry(QtCore.QRect(150, 390, 321, 16))
        self.CLOUDOUTPUT.setObjectName("CLOUDOUTPUT")
        self.BAROOUTPUT = QtWidgets.QLabel(Dialog)
        self.BAROOUTPUT.setGeometry(QtCore.QRect(210, 420, 271, 16))
        self.BAROOUTPUT.setObjectName("BAROOUTPUT")
        self.TEMPOUTPUT = QtWidgets.QLabel(Dialog)
        self.TEMPOUTPUT.setGeometry(QtCore.QRect(150, 450, 321, 16))
        self.TEMPOUTPUT.setObjectName("TEMPOUTPUT")
        self.DEWPOINT = QtWidgets.QLabel(Dialog)
        self.DEWPOINT.setGeometry(QtCore.QRect(140, 480, 331, 16))
        self.DEWPOINT.setObjectName("DEWPOINT")
        self.CONDITIONOUTPUT = QtWidgets.QLabel(Dialog)
        self.CONDITIONOUTPUT.setGeometry(QtCore.QRect(200, 510, 271, 16))
        self.CONDITIONOUTPUT.setObjectName("CONDITIONOUTPUT")
        self.DENSITYOUTPUT = QtWidgets.QLabel(Dialog)
        self.DENSITYOUTPUT.setGeometry(QtCore.QRect(190, 540, 281, 16))
        self.DENSITYOUTPUT.setObjectName("DENSITYOUTPUT")
        self.pushREQUEST = QtWidgets.QPushButton(Dialog, clicked=lambda:self.change_ui())
        self.pushREQUEST.setGeometry(QtCore.QRect(340, 70, 81, 31))
        self.pushREQUEST.setObjectName("pushREQUEST")
        self.SPACER = QtWidgets.QLabel(Dialog)
        self.SPACER.setGeometry(QtCore.QRect(20, 250, 431, 31))
        self.SPACER.setObjectName("SPACER")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(10, 630, 81, 81))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Icons/Windy.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(130, 630, 71, 81))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("Icons/High Temp.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(250, 630, 81, 71))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Icons/clouds.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(360, 630, 91, 71))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Icons/low visability.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(180, 590, 91, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(200, 580, 51, 51))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("Icons/Prohibited.png"))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(130, 630, 71, 81))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("Icons/low temperature.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_11.setHidden(True)
        self.label_17.setHidden(True)
        self.label_13.setHidden(True)
        self.label_14.setHidden(True)
        self.label_12.setHidden(True)
        self.label_16.setHidden(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ProjectPilotClearance"))
        self.label.setText(_translate("Dialog", "METAR REPORT(RAW):"))
        self.label_2.setText(_translate("Dialog", "TIME OF REPORT:"))
        self.label_3.setText(_translate("Dialog", "REPORTED WIND:"))
        self.label_4.setText(_translate("Dialog", "REPORTED VISABILITY:"))
        self.label_5.setText(_translate("Dialog", "REPORTED CLOUD BASES:"))
        self.label_6.setText(_translate("Dialog", "REPORTED BAROMETRIC PRESSURE:"))
        self.label_7.setText(_translate("Dialog", "REPORTED TEMPERATURE:"))
        self.label_8.setText(_translate("Dialog", "REPORTED DEWPOINT:"))
        self.label_9.setText(_translate("Dialog", "REPORTED WEATHER PHENOMENON:"))
        self.label_10.setText(_translate("Dialog", "PROJECTED DENSITY ALTITUDE:"))
        self.FAAWARNINGLABEL.setText(_translate("Dialog", "WARNING, THIS PROJECT IS IN BETA AND HAS NOT BEEN APPROVED BY THE FAA FOR USE"))
        self.INSTRUCTIONS.setText(_translate("Dialog", "Enter a ICAO code for the area you wish to view"))
        self.ICAO.setText(_translate("Dialog", "ICAO: "))
        self.METARRAWOUTPUT.setText(_translate("Dialog", "None"))
        self.TIMEOUTPUT.setText(_translate("Dialog", "None"))
        self.WINDOUTPUT.setText(_translate("Dialog", "None"))
        self.VISOUTPUT.setText(_translate("Dialog", "None"))
        self.CLOUDOUTPUT.setText(_translate("Dialog", "None"))
        self.BAROOUTPUT.setText(_translate("Dialog", "None"))
        self.TEMPOUTPUT.setText(_translate("Dialog", "None"))
        self.DEWPOINT.setText(_translate("Dialog", "None"))
        self.CONDITIONOUTPUT.setText(_translate("Dialog", "None"))
        self.DENSITYOUTPUT.setText(_translate("Dialog", "None"))
        self.pushREQUEST.setText(_translate("Dialog", "Push request"))
        self.SPACER.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-style:italic; text-decoration: underline;\">Broken down METAR request</span></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">VFR</span></p></body></html>"))
        self.GITHUBLINK.setText(_translate("Dialog", "If you need help with this program, Read the FILE: README.md,"))
        self.Extraspace.setText(_translate("Dialog", "This file contains information to help you")) ##REPUSH ME TO MAIN GITHUB!!!!!!!
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
